# Number of days of inactivity before an issue becomes stale
daysUntilStale: 7
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: question
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because the followup information requested has not been provided. It will be closed if no further activity occurs. Thank you for your report.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: This issue has been automatically closed because no followup information was provided. If the issue persists, please create a new issue.